#!/usr/bin/env bash
# generate-rtm.sh - Gera Requirements Traceability Matrix (RTM.yaml) a partir de frontmatter
#
# Usage: ./scripts/generate-rtm.sh [project_root] [output_file]
#
# Reads:
#   - PRD_04_UserJourneys.md (journeys frontmatter)
#   - PRD_08_FunctionalRequirements.md (functional_requirements frontmatter)
#   - ANEXO_A_ProcessDetails.md (processes frontmatter)
#   - ANEXO_B_DataModels.md (documents, invariants frontmatter)
#
# Generates:
#   - RTM.yaml: Dependency graph with bidirectional links
#
# Exit codes:
#   0 - RTM generated successfully
#   1 - Error during generation
#
# Dependencies: /usr/local/bin/yq (YAML processor)

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Project root and output file
PROJECT_ROOT="${1:-.}"
OUTPUT_FILE="${2:-$PROJECT_ROOT/RTM.yaml}"

# Temporary files
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "========================================="
echo "RTM Generation"
echo "========================================="
echo "Project: $PROJECT_ROOT"
echo "Output: $OUTPUT_FILE"
echo ""

# Function: Check if /usr/local/bin/yq is installed
check_dependencies() {
    if ! command -v /usr/local/bin/yq &> /dev/null; then
        echo -e "${RED}ERROR: /usr/local/bin/yq is not installed${NC}"
        echo "Install with: sudo wget -qO /usr/local/bin//usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod +x /usr/local/bin/yq"
        exit 1
    fi
}

# Function: Initialize RTM structure
initialize_rtm() {
    cat > "$TEMP_DIR/rtm_base.yaml" <<'EOF'
# Requirements Traceability Matrix (RTM)
# Auto-generated by scripts/generate-rtm.sh
# DO NOT EDIT MANUALLY - regenerate by running the script

metadata:
  generated_at: ""
  project_root: ""
  generator_version: "1.0"

# Nodes: All artifacts with IDs
nodes:
  vision_items: {}
  user_journeys: {}
  functional_requirements: {}
  success_criteria: {}
  processes: {}
  documents: {}
  invariants: {}

# Edges: Dependency relationships
edges:
  # Format: source_id -> [target_ids]
  upstream: {}    # Backward traceability (X motivated by Y)
  downstream: {}  # Forward traceability (X derives Z)
EOF

    # Set metadata
    /usr/local/bin/yq -i ".metadata.generated_at = \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.project_root = \"$PROJECT_ROOT\"" "$TEMP_DIR/rtm_base.yaml"
}

# Function: Extract User Journeys from PRD Section 4
extract_user_journeys() {
    local file="$PROJECT_ROOT/artifacts/PRD_04_UserJourneys.md"
    if [[ ! -f "$file" ]]; then
        file="$PROJECT_ROOT/templates/sections/PRD_04_UserJourneys-template.md"
    fi

    if [[ ! -f "$file" ]]; then
        echo -e "${YELLOW}WARNING: User Journeys file not found, skipping${NC}"
        return 0
    fi

    echo "Extracting User Journeys from $file..."

    local journey_count
    journey_count=$(/usr/local/bin/yq '.journeys | length' "$file" 2>/dev/null || echo "0")

    for ((i=0; i<journey_count; i++)); do
        local id title linked_frs linked_sc linked_vision

        id=$(/usr/local/bin/yq ".journeys[$i].id" "$file" 2>/dev/null | tr -d '"')
        title=$(/usr/local/bin/yq ".journeys[$i].title" "$file" 2>/dev/null | tr -d '"')
        linked_frs=$(/usr/local/bin/yq ".journeys[$i].linked_frs | @json" "$file" 2>/dev/null | tr -d '"')
        linked_sc=$(/usr/local/bin/yq ".journeys[$i].linked_success_criteria | @json" "$file" 2>/dev/null | tr -d '"')
        linked_vision=$(/usr/local/bin/yq ".journeys[$i].linked_vision | @json" "$file" 2>/dev/null | tr -d '"')

        if [[ -n "$id" && "$id" != "null" && "$id" != *"UJ-04-00"* ]]; then
            # Add node
            /usr/local/bin/yq -i ".nodes.user_journeys.\"$id\".title = \"$title\"" "$TEMP_DIR/rtm_base.yaml"

            # Add downstream edges (UJ -> FRs)
            if [[ "$linked_frs" != "[]" && "$linked_frs" != "null" ]]; then
                /usr/local/bin/yq -i ".edges.downstream.\"$id\" = $linked_frs" "$TEMP_DIR/rtm_base.yaml"
            fi

            # Add upstream edges (UJ <- Vision)
            if [[ "$linked_vision" != "[]" && "$linked_vision" != "null" ]]; then
                /usr/local/bin/yq -i ".edges.upstream.\"$id\" = $linked_vision" "$TEMP_DIR/rtm_base.yaml"
            fi
        fi
    done
}

# Function: Extract Functional Requirements from PRD Section 8
extract_functional_requirements() {
    local file="$PROJECT_ROOT/artifacts/PRD_08_FunctionalRequirements.md"
    if [[ ! -f "$file" ]]; then
        file="$PROJECT_ROOT/templates/sections/PRD_08_FunctionalRequirements-template.md"
    fi

    if [[ ! -f "$file" ]]; then
        echo -e "${YELLOW}WARNING: Functional Requirements file not found, skipping${NC}"
        return 0
    fi

    echo "Extracting Functional Requirements from $file..."

    local fr_count
    fr_count=$(/usr/local/bin/yq '.functional_requirements | length' "$file" 2>/dev/null || echo "0")

    for ((i=0; i<fr_count; i++)); do
        local id title source_journeys linked_invariants linked_processes linked_documents priority

        id=$(/usr/local/bin/yq ".functional_requirements[$i].id" "$file" 2>/dev/null | tr -d '"')
        title=$(/usr/local/bin/yq ".functional_requirements[$i].title" "$file" 2>/dev/null | tr -d '"')
        source_journeys=$(/usr/local/bin/yq ".functional_requirements[$i].source_journeys | @json" "$file" 2>/dev/null)
        linked_invariants=$(/usr/local/bin/yq ".functional_requirements[$i].linked_invariants | @json" "$file" 2>/dev/null)
        linked_processes=$(/usr/local/bin/yq ".functional_requirements[$i].linked_processes | @json" "$file" 2>/dev/null)
        linked_documents=$(/usr/local/bin/yq ".functional_requirements[$i].linked_documents | @json" "$file" 2>/dev/null)
        priority=$(/usr/local/bin/yq ".functional_requirements[$i].priority" "$file" 2>/dev/null | tr -d '"')

        if [[ -n "$id" && "$id" != "null" && "$id" != *"FR-00"* ]]; then
            # Add node
            /usr/local/bin/yq -i ".nodes.functional_requirements.\"$id\".title = \"$title\"" "$TEMP_DIR/rtm_base.yaml"
            /usr/local/bin/yq -i ".nodes.functional_requirements.\"$id\".priority = \"$priority\"" "$TEMP_DIR/rtm_base.yaml"

            # Upstream edges (FR <- Journeys)
            if [[ "$source_journeys" != "[]" && "$source_journeys" != "null" ]]; then
                /usr/local/bin/yq -i ".edges.upstream.\"$id\" = $source_journeys" "$TEMP_DIR/rtm_base.yaml"
            fi

            # Downstream edges (FR -> Invariants, Processes, Documents)
            local downstream="["
            local first=true

            if [[ "$linked_invariants" != "[]" && "$linked_invariants" != "null" ]]; then
                downstream+="$linked_invariants"
                first=false
            fi

            if [[ "$linked_processes" != "[]" && "$linked_processes" != "null" ]]; then
                if [[ "$first" == "false" ]]; then
                    downstream="${downstream%]}, ${linked_processes#[}"
                else
                    downstream+="$linked_processes"
                    first=false
                fi
            fi

            if [[ "$linked_documents" != "[]" && "$linked_documents" != "null" ]]; then
                if [[ "$first" == "false" ]]; then
                    downstream="${downstream%]}, ${linked_documents#[}"
                else
                    downstream+="$linked_documents"
                fi
            fi

            downstream+="]"

            if [[ "$downstream" != "[]" ]]; then
                /usr/local/bin/yq -i ".edges.downstream.\"$id\" = $downstream" "$TEMP_DIR/rtm_base.yaml"
            fi
        fi
    done
}

# Function: Extract Processes from ANEXO A
extract_processes() {
    local file="$PROJECT_ROOT/artifacts/ANEXO_A_ProcessDetails.md"
    if [[ ! -f "$file" ]]; then
        file="$PROJECT_ROOT/templates/ANEXO_A_ProcessDetails-template.md"
    fi

    if [[ ! -f "$file" ]]; then
        echo -e "${YELLOW}WARNING: Process Details file not found, skipping${NC}"
        return 0
    fi

    echo "Extracting Processes from $file..."

    local process_count
    process_count=$(/usr/local/bin/yq '.processes | length' "$file" 2>/dev/null || echo "0")

    for ((i=0; i<process_count; i++)); do
        local id title linked_frs linked_journeys linked_documents type

        id=$(/usr/local/bin/yq ".processes[$i].id" "$file" 2>/dev/null | tr -d '"')
        title=$(/usr/local/bin/yq ".processes[$i].title" "$file" 2>/dev/null | tr -d '"')
        linked_frs=$(/usr/local/bin/yq ".processes[$i].linked_frs | @json" "$file" 2>/dev/null)
        linked_journeys=$(/usr/local/bin/yq ".processes[$i].linked_journeys | @json" "$file" 2>/dev/null)
        linked_documents=$(/usr/local/bin/yq ".processes[$i].linked_documents | @json" "$file" 2>/dev/null)
        type=$(/usr/local/bin/yq ".processes[$i].type" "$file" 2>/dev/null | tr -d '"')

        if [[ -n "$id" && "$id" != "null" && "$id" != *"{bc_id}"* ]]; then
            # Add node
            /usr/local/bin/yq -i ".nodes.processes.\"$id\".title = \"$title\"" "$TEMP_DIR/rtm_base.yaml"
            /usr/local/bin/yq -i ".nodes.processes.\"$id\".type = \"$type\"" "$TEMP_DIR/rtm_base.yaml"

            # Upstream edges (Process <- FRs + Journeys)
            local upstream="["
            local first=true

            if [[ "$linked_frs" != "[]" && "$linked_frs" != "null" ]]; then
                upstream+="$linked_frs"
                first=false
            fi

            if [[ "$linked_journeys" != "[]" && "$linked_journeys" != "null" ]]; then
                if [[ "$first" == "false" ]]; then
                    upstream="${upstream%]}, ${linked_journeys#[}"
                else
                    upstream+="$linked_journeys"
                fi
            fi

            upstream+="]"

            if [[ "$upstream" != "[]" ]]; then
                /usr/local/bin/yq -i ".edges.upstream.\"$id\" = $upstream" "$TEMP_DIR/rtm_base.yaml"
            fi

            # Downstream edges (Process -> Documents)
            if [[ "$linked_documents" != "[]" && "$linked_documents" != "null" ]]; then
                /usr/local/bin/yq -i ".edges.downstream.\"$id\" = $linked_documents" "$TEMP_DIR/rtm_base.yaml"
            fi
        fi
    done
}

# Function: Extract Documents and Invariants from ANEXO B
extract_documents_and_invariants() {
    local file="$PROJECT_ROOT/artifacts/ANEXO_B_DataModels.md"
    if [[ ! -f "$file" ]]; then
        file="$PROJECT_ROOT/templates/ANEXO_B_DataModels-template.md"
    fi

    if [[ ! -f "$file" ]]; then
        echo -e "${YELLOW}WARNING: Data Models file not found, skipping${NC}"
        return 0
    fi

    echo "Extracting Documents and Invariants from $file..."

    # Documents
    local doc_count
    doc_count=$(/usr/local/bin/yq '.documents | length' "$file" 2>/dev/null || echo "0")

    for ((i=0; i<doc_count; i++)); do
        local id negocio linked_frs linked_journeys linked_processes type

        id=$(/usr/local/bin/yq ".documents[$i].id" "$file" 2>/dev/null | tr -d '"')
        negocio=$(/usr/local/bin/yq ".documents[$i].negocio" "$file" 2>/dev/null | tr -d '"')
        linked_frs=$(/usr/local/bin/yq ".documents[$i].linked_frs | @json" "$file" 2>/dev/null)
        linked_journeys=$(/usr/local/bin/yq ".documents[$i].linked_journeys | @json" "$file" 2>/dev/null)
        linked_processes=$(/usr/local/bin/yq ".documents[$i].linked_processes | @json" "$file" 2>/dev/null)
        type=$(/usr/local/bin/yq ".documents[$i].type" "$file" 2>/dev/null | tr -d '"')

        if [[ -n "$id" && "$id" != "null" && "$id" != *"{bc_id}"* && "$id" != *"{TechnicalName}"* ]]; then
            # Add node
            /usr/local/bin/yq -i ".nodes.documents.\"$id\".negocio = \"$negocio\"" "$TEMP_DIR/rtm_base.yaml"
            /usr/local/bin/yq -i ".nodes.documents.\"$id\".type = \"$type\"" "$TEMP_DIR/rtm_base.yaml"

            # Upstream edges (Document <- FRs + Journeys + Processes)
            local upstream="["
            local first=true

            if [[ "$linked_frs" != "[]" && "$linked_frs" != "null" ]]; then
                upstream+="$linked_frs"
                first=false
            fi

            if [[ "$linked_journeys" != "[]" && "$linked_journeys" != "null" ]]; then
                if [[ "$first" == "false" ]]; then
                    upstream="${upstream%]}, ${linked_journeys#[}"
                else
                    upstream+="$linked_journeys"
                    first=false
                fi
            fi

            if [[ "$linked_processes" != "[]" && "$linked_processes" != "null" ]]; then
                if [[ "$first" == "false" ]]; then
                    upstream="${upstream%]}, ${linked_processes#[}"
                else
                    upstream+="$linked_processes"
                fi
            fi

            upstream+="]"

            if [[ "$upstream" != "[]" ]]; then
                /usr/local/bin/yq -i ".edges.upstream.\"$id\" = $upstream" "$TEMP_DIR/rtm_base.yaml"
            fi
        fi
    done

    # Invariants
    local inv_count
    inv_count=$(/usr/local/bin/yq '.invariants | length' "$file" 2>/dev/null || echo "0")

    for ((i=0; i<inv_count; i++)); do
        local id description severity linked_documents linked_frs

        id=$(/usr/local/bin/yq ".invariants[$i].id" "$file" 2>/dev/null | tr -d '"')
        description=$(/usr/local/bin/yq ".invariants[$i].description" "$file" 2>/dev/null | tr -d '"')
        severity=$(/usr/local/bin/yq ".invariants[$i].severity" "$file" 2>/dev/null | tr -d '"')
        linked_documents=$(/usr/local/bin/yq ".invariants[$i].linked_documents | @json" "$file" 2>/dev/null)
        linked_frs=$(/usr/local/bin/yq ".invariants[$i].linked_frs | @json" "$file" 2>/dev/null)

        if [[ -n "$id" && "$id" != "null" ]]; then
            # Add node
            /usr/local/bin/yq -i ".nodes.invariants.\"$id\".description = \"$description\"" "$TEMP_DIR/rtm_base.yaml"
            /usr/local/bin/yq -i ".nodes.invariants.\"$id\".severity = \"$severity\"" "$TEMP_DIR/rtm_base.yaml"

            # Upstream edges (Invariant <- FRs)
            if [[ "$linked_frs" != "[]" && "$linked_frs" != "null" ]]; then
                /usr/local/bin/yq -i ".edges.upstream.\"$id\" = $linked_frs" "$TEMP_DIR/rtm_base.yaml"
            fi

            # Downstream edges (Invariant -> Documents)
            if [[ "$linked_documents" != "[]" && "$linked_documents" != "null" ]]; then
                /usr/local/bin/yq -i ".edges.downstream.\"$id\" = $linked_documents" "$TEMP_DIR/rtm_base.yaml"
            fi
        fi
    done
}

# Function: Calculate statistics
calculate_statistics() {
    echo ""
    echo "Calculating statistics..."

    local total_nodes=0
    local total_edges=0

    # Count nodes
    local vision_count journeys_count frs_count processes_count docs_count invs_count

    vision_count=$(/usr/local/bin/yq '.nodes.vision_items | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")
    journeys_count=$(/usr/local/bin/yq '.nodes.user_journeys | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")
    frs_count=$(/usr/local/bin/yq '.nodes.functional_requirements | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")
    processes_count=$(/usr/local/bin/yq '.nodes.processes | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")
    docs_count=$(/usr/local/bin/yq '.nodes.documents | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")
    invs_count=$(/usr/local/bin/yq '.nodes.invariants | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")

    total_nodes=$((vision_count + journeys_count + frs_count + processes_count + docs_count + invs_count))

    # Count edges
    local upstream_count downstream_count

    upstream_count=$(/usr/local/bin/yq '.edges.upstream | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")
    downstream_count=$(/usr/local/bin/yq '.edges.downstream | length' "$TEMP_DIR/rtm_base.yaml" 2>/dev/null || echo "0")

    total_edges=$((upstream_count + downstream_count))

    # Add statistics to RTM
    /usr/local/bin/yq -i ".metadata.statistics.total_nodes = $total_nodes" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.total_edges = $total_edges" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.nodes_by_type.vision_items = $vision_count" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.nodes_by_type.user_journeys = $journeys_count" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.nodes_by_type.functional_requirements = $frs_count" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.nodes_by_type.processes = $processes_count" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.nodes_by_type.documents = $docs_count" "$TEMP_DIR/rtm_base.yaml"
    /usr/local/bin/yq -i ".metadata.statistics.nodes_by_type.invariants = $invs_count" "$TEMP_DIR/rtm_base.yaml"

    echo "  Total nodes: $total_nodes"
    echo "  Total edges: $total_edges (upstream: $upstream_count, downstream: $downstream_count)"
}

# Main execution
main() {
    check_dependencies
    initialize_rtm

    echo ""
    echo "Extracting nodes and edges..."
    echo ""

    extract_user_journeys
    extract_functional_requirements
    extract_processes
    extract_documents_and_invariants

    calculate_statistics

    # Write final RTM to output file
    cp "$TEMP_DIR/rtm_base.yaml" "$OUTPUT_FILE"

    echo ""
    echo "========================================="
    echo -e "${GREEN}✅ RTM Generated Successfully${NC}"
    echo "========================================="
    echo "Output: $OUTPUT_FILE"
    echo ""
    echo "Next steps:"
    echo "  1. Run scripts/validate-links.sh to check for orphan links"
    echo "  2. Run scripts/impact-analysis.sh {id} to analyze change impact"
}

# Run main
main
